# Generated by Django 2.1.1 on 2018-10-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.TextField(default='This is cool!'),
        ),
    ]
